"""Temporary testing ground for PawPal+.

Run from the terminal to verify the logic layer works end to end:

    python main.py

It creates an owner with two pets and several tasks, then prints today's
schedule generated by the Scheduler.
"""

from pawpal_system import Owner, Pet, Scheduler, Task


def print_schedule(owner: Owner, plan: dict, available_minutes: int) -> None:
    """Print today's schedule as a clean, aligned table in the terminal."""
    items = plan["items"]
    skipped = plan["skipped"]

    # Size the TASK column to the longest title so everything lines up.
    titles = [item["task"].title for item in items] + [t.title for t in skipped]
    task_width = max([len("TASK")] + [len(t) for t in titles])

    header = f"  Today's Schedule for {owner.name}"
    subtitle = (
        f"  Pets: {', '.join(pet.name for pet in owner.pets)}"
        f"   |   Time budget: {available_minutes} min"
    )
    width = max(len(header), len(subtitle), task_width + 30)

    print("=" * width)
    print(header)
    print(subtitle)
    print("=" * width)

    if items:
        print(f"  {'TIME':<6}  {'TASK':<{task_width}}  {'MINS':>5}  PRIORITY")
        print(f"  {'-' * 6}  {'-' * task_width}  {'-' * 5}  {'-' * 8}")
        for item in items:
            task = item["task"]
            print(
                f"  {item['time']:<6}  {task.title:<{task_width}}  "
                f"{task.duration_minutes:>5}  {task.priority.upper()}"
            )
    else:
        print("  (nothing fits in the available time)")

    if skipped:
        print()
        print("  Skipped (not enough time):")
        for task in skipped:
            print(f"    - {task.title} ({task.duration_minutes} min, {task.priority})")

    print("-" * width)
    print(
        f"  Scheduled {plan['total_minutes']} of {available_minutes} min"
        f"   |   {len(items)} task(s) planned, {len(skipped)} skipped"
    )


def main() -> None:
    # 1. Create an owner.
    owner = Owner(name="Jordan", day_start_hour=8)

    # 2. Create at least two pets.
    dog = Pet(name="Mochi", species="dog", breed="Corgi")
    cat = Pet(name="Simba", species="cat")

    # 3. Add at least three tasks with different times (durations).
    dog.add_task(Task("Morning walk", duration_minutes=30, priority="high"))
    dog.add_task(Task("Feeding", duration_minutes=10, priority="high"))
    dog.add_task(Task("Enrichment puzzle", duration_minutes=20, priority="low"))
    cat.add_task(Task("Litter box", duration_minutes=5, priority="high"))
    cat.add_task(Task("Grooming", duration_minutes=45, priority="medium"))

    owner.add_pet(dog)
    owner.add_pet(cat)

    # 4. Build and print "Today's Schedule".
    scheduler = Scheduler()
    available_minutes = 90  # time the owner has available today
    plan = scheduler.plan_for_owner(owner, available_minutes=available_minutes)

    print_schedule(owner, plan, available_minutes)


if __name__ == "__main__":
    main()
