"""Temporary testing ground for PawPal+.

Run from the terminal to verify the logic layer works end to end:

    python main.py

It creates an owner with two pets and several tasks, then prints today's
schedule generated by the Scheduler.
"""

from pawpal_system import Owner, Pet, Scheduler, Task


def print_schedule(owner: Owner, plan: dict, available_minutes: int) -> None:
    """Print today's schedule as a clean, aligned table in the terminal."""
    items = plan["items"]
    skipped = plan["skipped"]

    # Size the TASK column to the longest title so everything lines up.
    titles = [item["task"].title for item in items] + [t.title for t in skipped]
    task_width = max([len("TASK")] + [len(t) for t in titles])

    header = f"  Today's Schedule for {owner.name}"
    subtitle = (
        f"  Pets: {', '.join(pet.name for pet in owner.pets)}"
        f"   |   Time budget: {available_minutes} min"
    )
    width = max(len(header), len(subtitle), task_width + 30)

    print("=" * width)
    print(header)
    print(subtitle)
    print("=" * width)

    if items:
        print(f"  {'TIME':<6}  {'TASK':<{task_width}}  {'MINS':>5}  PRIORITY")
        print(f"  {'-' * 6}  {'-' * task_width}  {'-' * 5}  {'-' * 8}")
        for item in items:
            task = item["task"]
            print(
                f"  {item['time']:<6}  {task.title:<{task_width}}  "
                f"{task.duration_minutes:>5}  {task.priority.upper()}"
            )
    else:
        print("  (nothing fits in the available time)")

    if skipped:
        print()
        print("  Skipped (not enough time):")
        for task in skipped:
            print(f"    - {task.title} ({task.duration_minutes} min, {task.priority})")

    print("-" * width)
    print(
        f"  Scheduled {plan['total_minutes']} of {available_minutes} min"
        f"   |   {len(items)} task(s) planned, {len(skipped)} skipped"
    )


def main() -> None:
    scheduler = Scheduler()

    # 1. Create an owner.
    owner = Owner(name="Jordan", day_start_hour=8)

    # 2. Create at least two pets.
    dog = Pet(name="Mochi", species="dog", breed="Corgi")
    cat = Pet(name="Simba", species="cat")

    # 3. Add tasks OUT OF ORDER (note the times are not chronological) so we can
    #    prove sort_by_time() actually reorders them.
    dog.add_task(Task("Evening walk", 30, "high", time="18:00"))
    dog.add_task(Task("Morning walk", 30, "high", time="08:00"))
    dog.add_task(Task("Lunch feeding", 10, "medium", time="12:30"))
    cat.add_task(Task("Litter box", 5, "high", time="07:30"))
    # This one clashes with the dog's Morning walk (both at 08:00) — a conflict.
    cat.add_task(Task("Vet phone call", 15, "medium", time="08:00"))
    grooming = Task("Grooming", 45, "medium", time="15:00")
    grooming.mark_done()  # already completed today
    cat.add_task(grooming)

    owner.add_pet(dog)
    owner.add_pet(cat)

    # CONFLICT DETECTION: warn (don't crash) if any tasks clash.
    print("=== Conflict check ===")
    warnings = scheduler.find_conflicts(owner.all_tasks(), available_minutes=90)
    if warnings:
        for warning in warnings:
            print(f"  ⚠️  {warning}")
    else:
        print("  No conflicts detected.")
    print()

    # 4. SORTING: order every task chronologically by its "HH:MM" time.
    print("=== All tasks, sorted by time ===")
    for task in scheduler.sort_by_time(owner.all_tasks()):
        print(f"  {task.time}  {task.title} ({task.duration_minutes} min)")

    # 5. FILTERING by completion status.
    pending = scheduler.filter_by_status(owner.all_tasks(), completed=False)
    done = scheduler.filter_by_status(owner.all_tasks(), completed=True)
    print(f"\n=== Pending tasks ({len(pending)}) ===")
    for task in scheduler.sort_by_time(pending):
        print(f"  {task.time}  {task.title}")
    print(f"\n=== Completed tasks ({len(done)}) ===")
    for task in done:
        print(f"  {task.time}  {task.title}")

    # 6. FILTERING by pet name.
    print("\n=== Mochi's tasks ===")
    for task in scheduler.sort_by_time(owner.tasks_for_pet("Mochi")):
        print(f"  {task.time}  {task.title}")

    # 7. Build and print "Today's Schedule".
    print()
    available_minutes = 90  # time the owner has available today
    plan = scheduler.plan_for_owner(owner, available_minutes=available_minutes)
    print_schedule(owner, plan, available_minutes)


if __name__ == "__main__":
    main()
